// MUI Imports
import Typography from '@mui/material/Typography'
import Chip from '@mui/material/Chip'

// Component Imports
import LinkButton from '@/components/site/LinkButton'
import PageHeader from '@/components/site/PageHeader'
import Caveat from '@/components/site/Caveat'
import SectionCard from '@/components/site/SectionCard'

export const metadata = {
  title: 'Concepts — FL with non-IID data',
  description:
    'Short explainers for non-IID data, Hellinger distance, the four aggregation strategies, differential privacy, secure aggregation and gradient inversion.'
}

const Page = () => (
  <div className='flex flex-col'>
    <PageHeader
      eyebrow='Background'
      title='Concepts'
      lede='Short explanations of the ideas the results depend on, each pointing at the runs that demonstrate them. Written for a reader who knows machine learning but not this subfield.'
    />

    <div className='flex flex-col gap-6'>
      <SectionCard icon='tabler-chart-pie' color='primary' title='Non-IID data, and the four ways it goes wrong'>
          <Typography>
            Federated learning assumes data stays where it was collected. That assumption has a consequence: each
            client&apos;s data reflects wherever it came from, so the clients do not hold independent, identically
            distributed samples of one population. A hospital in one region sees different case mixes from a hospital
            in another.
          </Typography>
          <Typography>This study induces heterogeneity in three distinguishable ways:</Typography>
          <div className='flex flex-col gap-2 pis-4'>
            <Typography variant='body2'>
              <strong>Label skew</strong> — clients hold different class proportions. Generated by a Dirichlet split
              with concentration α: large α approaches an even split, small α concentrates each client on a few
              classes.
            </Typography>
            <Typography variant='body2'>
              <strong>Pathological skew</strong> — the extreme case, one class per client. Every client&apos;s local
              optimum points somewhere the global optimum is not.
            </Typography>
            <Typography variant='body2'>
              <strong>Quantity skew</strong> — clients hold different <em>amounts</em> of data while class proportions
              stay roughly even. Generated here with β = 0.5.
            </Typography>
          </div>
          <Typography variant='body2' color='text.secondary'>
            These are not interchangeable. Quantity skew turns out to be mild by the measure this study uses, while the
            pathological split is severe — which is why heterogeneity is reported as a measured quantity rather than by
            the name of the protocol.
          </Typography>
      </SectionCard>

      <SectionCard
        icon='tabler-ruler-measure'
        color='info'
        title='Hellinger distance'
        subtitle='The measured quantity that heterogeneity is reported as'
      >
          <Typography>
            The Hellinger distance between two probability distributions is a number in [0, 1]: zero when they are
            identical, one when they share no support. Here it is computed between each client&apos;s label
            distribution and the global label distribution, then averaged across clients.
          </Typography>
          <Typography>
            It is used instead of the partition parameter because the parameter is what was <em>requested</em> and the
            distance is what was <em>obtained</em>. The same α produces different splits under different seeds, and
            protocols with quite different names can land close together:
          </Typography>
          <div className='flex gap-2 flex-wrap'>
            <Chip size='small' variant='tonal' label='Dirichlet α=100 → H ≈ 0.03' />
            <Chip size='small' variant='tonal' label='quantity β=0.5 → H ≈ 0.10' />
            <Chip size='small' variant='tonal' label='Dirichlet α=1.0 → H ≈ 0.31' />
            <Chip size='small' variant='tonal' color='warning' label='Dirichlet α=0.1 → H ≈ 0.65' />
            <Chip size='small' variant='tonal' color='error' label='pathological → H ≈ 0.83' />
          </div>
          <Typography variant='body2' color='text.secondary'>
            Note that quantity skew sits near the homogeneous end. It varies how much data clients hold, not what is in
            it, so a label-distribution measure registers it as mild — which is the correct reading, and one that using
            α alone would have obscured.
          </Typography>
          <LinkButton href='/rq1' size='small' variant='tonal' className='self-start'>
            See accuracy plotted against it
          </LinkButton>
      </SectionCard>

      <SectionCard icon='tabler-git-merge' color='secondary' title='The four aggregation strategies'>
          <div>
            <Typography variant='subtitle2'>FedAvg</Typography>
            <Typography variant='body2'>
              The baseline. Clients train locally for a few epochs; the server averages their weights in proportion to
              how much data each holds. Simple, and the thing everything else is trying to improve on. Under
              heterogeneity, clients drift towards their own local optima and the average of those drifted models is
              not the model that a pooled dataset would have produced.
            </Typography>
          </div>
          <div>
            <Typography variant='subtitle2'>FedProx</Typography>
            <Typography variant='body2'>
              FedAvg plus a proximal term penalising how far a client&apos;s local model moves from the global model it
              started the round with. It restrains drift rather than correcting it.
            </Typography>
          </div>
          <div>
            <Typography variant='subtitle2'>SCAFFOLD</Typography>
            <Typography variant='body2'>
              Estimates the drift explicitly, as a control variate carried by each client and by the server, and
              subtracts it from the local update. In principle this corrects client drift rather than merely
              penalising it. In this study it is the strategy that struggles most as heterogeneity rises, and on one
              configuration it diverges outright.
            </Typography>
          </div>
          <div>
            <Typography variant='subtitle2'>MOON</Typography>
            <Typography variant='body2'>
              Adds a contrastive term in representation space, pulling a client&apos;s representation towards the
              global model&apos;s and away from its own previous one.
            </Typography>
          </div>
          <div>
            <Typography variant='subtitle2'>
              FedAvgM{' '}
              <Chip size='small' variant='tonal' color='secondary' label='a configuration, not a fifth strategy' />
            </Typography>
            <Typography variant='body2'>
              FedAvg with momentum applied to the server-side update. It appears in the results as a configuration of
              FedAvg — its recorded config carries <code>strategy: &quot;fedavg&quot;</code> and adds only{' '}
              <code>server_momentum</code> and <code>server_lr</code> — and should be read as an ablation of FedAvg
              rather than as a competitor to the other three.
            </Typography>
          </div>
      </SectionCard>

      <SectionCard icon='tabler-lock' color='success' title='Differential privacy and ε'>
          <Typography>
            Differential privacy bounds how much any single record can influence what is released. The bound is ε:
            smaller means stronger privacy and, in practice, more noise added and more accuracy lost. In federated
            learning it is usually applied by clipping each update to a fixed norm and then adding calibrated noise.
          </Typography>
          <Typography variant='body2' color='text.secondary'>
            The granularity matters as much as the value. Protecting a single training sample, a single user, or an
            entire silo are different guarantees at the same nominal ε, and with only 15 clients the silo-level
            guarantee is the hard one — which is what Phase D is designed to examine.
          </Typography>
          <Caveat severity='info' title='No results yet'>
            Phases B and D have not been run. Nothing on this site reports an accuracy cost for differential privacy.
          </Caveat>
      </SectionCard>

      <SectionCard icon='tabler-shield-check' color='info' title='Secure aggregation'>
          <Typography>
            Differential privacy limits what can be inferred from the aggregate. Secure aggregation addresses a
            different exposure: it stops the server from seeing any individual update at all. Clients add pairwise
            masks that cancel when summed, so the server can compute the sum without observing the terms.
          </Typography>
          <Typography variant='body2' color='text.secondary'>
            The two are complementary rather than alternatives — masking hides individual contributions from the
            server, and differential privacy bounds what the revealed sum leaks. The cost of masking is paid in
            communication rather than accuracy.
          </Typography>
      </SectionCard>

      <SectionCard icon='tabler-shield-lock' color='error' title='Gradient inversion, and why higher PSNR is worse'>
          <Typography>
            A gradient inversion attack starts from what a client transmits and optimises a synthetic input until its
            gradient matches. If it succeeds, the transmitted update was not the privacy-preserving abstraction it was
            assumed to be — it was the training data in another form.
          </Typography>
          <Typography>
            Reconstruction quality is measured with PSNR, in decibels. <strong>Higher PSNR means worse privacy</strong>
            , which reverses the usual reading of the metric, so it needs reference points to be interpretable at all:
          </Typography>
          <div className='flex gap-2 flex-wrap'>
            <Chip size='small' variant='tonal' color='success' label='random image — 8.7 dB' />
            <Chip size='small' variant='tonal' color='success' label='flat grey — 13.82 dB' />
            <Chip size='small' variant='tonal' color='error' label='lightly noised copy — 26.1 dB' />
          </div>
          <Typography variant='body2' color='text.secondary'>
            A reconstruction at or below 13.82 dB has failed — it carries no more information than a blank image. A
            reconstruction near 26 dB is a recognisable copy of the original. Without those anchors a PSNR figure is
            uninterpretable, so they appear wherever one is reported.
          </Typography>
          <Caveat severity='info' title='No results yet'>
            Phase E has not been run. No reconstruction or PSNR figures appear on this site.
          </Caveat>
      </SectionCard>
    </div>
  </div>
)

export default Page
