'use client'

// React Imports
import { useState } from 'react'

// MUI Imports
import Button from '@mui/material/Button'
import Tooltip from '@mui/material/Tooltip'

type Cell = string | number | boolean | null | undefined

type Props = {
  /** Without extension; ".csv" is appended. */
  filename: string
  columns: string[]
  rows: Cell[][]
  /** Run directories these numbers came from, listed in the file header. */
  sources?: string[]
  label?: string
}

const escapeCell = (v: Cell) => {
  if (v === null || v === undefined) return ''
  const s = String(v)

  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s
}

/*
 * Downloads the exact numbers behind one figure or table.
 *
 * The CSV is built in the browser from the same values the component just
 * rendered, rather than from a file generated at build time. That is deliberate:
 * most figures here are aggregates — means across strategies, spreads across
 * partitions — and a build script computing them separately would be a second
 * implementation of logic that already lives in src/lib/results.ts. The two
 * would drift, and the drift would be silent.
 *
 * Building from the rendered values makes disagreement impossible: what
 * downloads is what is on screen. The per-run source files it derives from are
 * published separately and named in the header, so the chain back to the
 * recorded data stays intact.
 *
 * No fetch and no zipping — a Blob of a few kilobytes, assembled on click.
 */
const FigureData = ({ filename, columns, rows, sources, label = 'Data' }: Props) => {
  const [done, setDone] = useState(false)

  const download = () => {
    const header: string[] = []

    header.push(`# ${filename}`)
    header.push('# Generated by the results explorer from the values shown on the page.')

    if (sources?.length) {
      header.push(`# Source runs (${sources.length}): ${sources.join(' ')}`)
      header.push('# Each of those runs publishes its own raw files under /data/runs/<run>/.')
    }

    const csv = [
      ...header,
      columns.join(','),
      ...rows.map(r => r.map(escapeCell).join(','))
    ].join('\n')

    const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8' }))
    const a = document.createElement('a')

    a.href = url
    a.download = `${filename}.csv`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)

    setDone(true)
    setTimeout(() => setDone(false), 2000)
  }

  return (
    <Tooltip title={`Download the ${rows.length} rows behind this${sources?.length ? `, from ${sources.length} run${sources.length === 1 ? '' : 's'}` : ''}`}>
      <Button
        size='small'
        variant='text'
        color='secondary'
        onClick={download}
        startIcon={<i className={done ? 'tabler-check' : 'tabler-table-export'} />}
      >
        {done ? 'Downloaded' : label}
      </Button>
    </Tooltip>
  )
}

export default FigureData
